image: "rust:latest"

test:cargo:
  id_tokens:
    ID_TOKEN:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --workspace
    - RUST_LOG=debug cargo run -p ci-id-bin sigstore
    - RUST_LOG=debug cargo run -p ci-id-bin
