[package]
name = "ci-id"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
regex = "1.11.1"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.213", features = ["derive"] }


